<div id="content">
    <div class="content-bg">
        <!-- start contacts block -->
        <div class="big-block">
            <h1><?php echo "What We Do" ?></h1>
            <div id="contact_us" class="contact">
                <?php print form::open(NULL, array('id' => 'contactForm', 'name' => 'contactForm')); ?>
                <div class="report_row">
                    <strong>Introduction</strong><br />
                    The Tree Watch Dog came up as an idea that was developed for the APPS 4 AFRICA challenge to battle out the main cause and impact of Climate Change. 
                    <br /><br />
                    A team of 3 extra ordinary brilliant young men set forth to come up with a solution to analyze the rate of deforestation and afforestration through engaging the public into reporting these incidences since they are more on ground and they developed the Tree Watch Dog after battling up there minds to come up with a model to track and analyse the trees that are being cut down and planted naming their crowd sourcing tool the "Tree Watch Dog" which is strongly based on the reported tree incidents that are submitted to the system.

                </div>
                <div class="report_row">
                    <strong>Problem Statement</strong><br />
                    It was noted that Deforestation leading to Desertification is one of the major causes and factors of climate change. But there were no genuine and reliable reports portraying the data showing the rate at which trees are depleted and planted from there respective locations and habitations.                 </div>
                <div class="report_row">
                    <strong>Methodology</strong><br />
                    The methods of reporting tree incidents done from various sources and locations include reports that come through web and phones where country citizens can report any incidents that they have seen relating to the destruction of the trees or tree planting in their regions. These are the main methods of reporting due to the fact that in Africa, it has been noted that over 70% of the population own phones and this is increasing with time. This justifies why the team is intending to bring the reporting services closer to the people as close as having the application running on any ones phone. 
                    <br /><br />
                    It is through this that the team is also developing the Mobile Platform for the system. This will run on Smart Phones including Android, Nokia phones and java enabled phones. 
                </div>
                <div class="report_row">
                    <strong>Incentives of the system</strong><br />
                    Furthermore, the system also engages the public in reporting the tree incidences (Deforestation and Afforestation) and through this the concerned bodies of the given countries (for example National Forest Authority in Uganda) which is strongly attributed to planting trees and prevention of unnecessary tree cut downs to mention may think of rewarding active citizens who really care and engage in reporting. This will encourage the public at large to engage in reporting the tree incidents that do happen around them so as to be able to benefit from this.
                </div>
                <div class="report_row">
                    <strong>Users</strong><br />
                    The system is open for use by anyone at any one point. First and foremost the public can post data about the trees that are cut down and the trees that are being planted in their areas. Secondly, the system can be used by Proffesionals in the field of Forestry, National Governing bodies like the National Forest Associations eg NFA in Uganda, Researchers are all welcome to use the system.                </div>
                <div class="report_row">
                    <strong>Description of the system</strong><br />
                    The System involves a platform where the public can submit reports of tree incidents. Before the Reports are populated on the map for public view, they all go through a verification and acknowedlgement process which is done by the system administrators in the given country for example NFA in Uganda. This is done so to obtain the real actual picture on ground so that the data collected is reliable and credible. At times they may need to move to the place/ region where the incident was reported from or they may use feed back and comments from the public on the given reported incident. Immediately the verification process is done, the systems auto generates any analysis which is populated on the web and the necssary reports and graphs are produced which are accessed by the public. And from these data and analysis, good decisions about desertications can be made since the reliable figures and statistics are generated by the system.
                    <br /><br />
                    Different scholars are able to review the reports and also derive the trend of the destruction of the trees in a given region. The system is actually open to be used in any country and would be appropriate when administered by the concerned bodies in the countries, for example NFA in Uganda.
                    <br /><br />
                    The developers are willing to add in extra features as proposed by different partners.  
                </div>
                <div class="report_row">
                    <strong>License</strong><br />
                    The system is an open source system and anyone who would like to modify or make enhancements on the system should contact the team and render there help or assistance to enable the developers grow and build comprehensive interactive system based on the knowledge of crowd sourcing.                 </div>
                <?php print form::close(); ?>
            </div>

        </div>
        <!-- end contacts block -->
    </div>
</div>